services:
  app:
    build: .
    container_name: fintech-app
    ports:
      - "8080:8080"
    env_file:
      - .env

    depends_on:
      - mysql
      - redis

    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: fintech-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql-data:/var/lib/mysql

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fintech-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

volumes:
  mysql-data: