services:
  app:
    build: .
    container_name: fintech-app
    ports:
      - "8080:8080"
    env_file:
      - .env

    depends_on:
      - mysql
      - redis

    restart: unless-stopped

  postgres:
    image: postgres:17-alpine

    environment:
      POSTGRES_DB=fintech_db
      POSTGRES_USER=fintech
      POSTGRES_PASSWORD=fintech

    volumes:
      - mysql-data:/var/lib/mysql

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fintech-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

volumes:
  mysql-data: