spring.application.name=fintech
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=false
management.endpoints.web.exposure.include=health,info
app.base-url=${APP_BASE_URL}
# JWT settings
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
logging.level.org.springframework.security=DEBUG

#redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

#smtp
brevo.api-key=${BREVO_API_KEY}
brevo.base-url=${BREVO_BASE_URL}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME}

#server
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
