# ==========================
# Application
# ==========================
spring.application.name=fintech

# ==========================
# H2 Database
# ==========================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop

# ==========================
# JWT
# ==========================
jwt.secret=test-secret-key-test-secret-key-test-secret-key-123456789
jwt.expiration-ms=3600000

# ==========================
# Redis
# ==========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================
# Application URL
# ==========================
app.base-url=http://localhost:8080

# ==========================
# Brevo (Dummy values)
# ==========================
brevo.api-key=test-api-key
brevo.base-url=https://api.brevo.com/v3
brevo.sender-email=test@example.com
brevo.sender-name=Test

# ==========================
# Logging
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s